module.exports = {
  purge: {
    content: ['./src/**/*.{js,ts,jsx,tsx}', './pages/**/*.{js,ts,jsx,tsx}'],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      xs: '320px',
      sm: '641px',
      md: '768px',
      lg: '1240px',
      // xl: '1281px',
      // '2xl': '1537px'
    },
    fontFamily: {
      sans: ['Quicksand', 'sans-serif'],
      serif: ['DM Serif Display', 'serif'],
    },
    zIndex: {
      1: -1,
      0: 0,
      10: 10,
      20: 20,
      9: 9,
      99: 99,
      999: 999,
      9999: '9999',
      auto: 'auto',
      modal: '999999',
    },
    opacity: {
      0: '0',
      25: '.25',
      75: '.75',
      10: '.1',
      20: '.2',
      30: '.3',
      40: '.4',
      50: '.5',
      60: '.6',
      70: '.7',
      80: '.8',
      90: '.9',
      100: '1',
    },
    extend: {
      fontSize: {
        '1sm': '13px',
        '1xs': '11px',
        '2xs': '10px',
        '3xs': '9px',
        '4xs': '8px',
        md: '15px',
        '2.5xl': '1.75rem',
      },
      letterSpacing: {
        'extra-wide': '0.45em',
        loose: '0.7em',
      },
      divideWidth: {
        0.5: '0.5px',
        3: '3px',
      },
      borderWidth: {
        0.5: '0.5px',
        3: '3px',
      },
      color: {},
    },
  },
  variants: {
    extend: {},
  },
  corePlugins: {
    // ...
    placeholderColor: false,
    animation: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropFilter: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    backgroundBlendMode: false,
    backgroundOrigin: false,
    blur: false,
    boxDecorationBreak: false,
    brightness: false,
    caretColor: false,
    clear: false,
    contrast: false,
    divideOpacity: false,
    divideStyle: false,
    // filter: false,
    float: false,
    fontVariantNumeric: false,
    gradientColorStops: false,
    grayscale: false,
    hueRotate: false,
    isolation: false,
    mixBlendMode: false,
    overscrollBehavior: false,
    placeItems: false,
    placeSelf: false,
    saturate: false,
    sepia: false,
    skew: false,
    stroke: false,
    strokeWidth: false,
    tableLayout: false,
  },
  plugins: [require('tailwindcss')],
};
